export const CHANGE_URL_FIELD = 'CHANGE_URL_FIELD';

export const IMAGE_DISPLAY = 'IMAGE_DISPLAY';

export const API_CALL_PENDING = 'API_CALL_PENDING';
export const API_CALL_SUCCESS_BOX = 'API_CALL_SUCCESS_BOX';
export const API_CALL_SUCCESS_DEM = 'API_CALL_SUCCESS_DEM';
export const API_CALL_FAILED = 'API_CALL_FAILED';

export const SELECTED_FACE_BOX = 'SELECTED_FACE_BOX';
export const SELECTED_FACE_DEM = 'SELECTED_FACE_DEM';